### ISSUE TITLE
Character encoding issue when using Persian in feed title and description

### ISSUE THREAD

**Issue by mark-up** [NinjaForge/Ninja-RSS-Syndicator#1]
> I use persian ( UTF8 ) language and when I write the feed title and description in persian , after saving it'll be broken and it shows "????????????" instead of persian characters ....

http://ninjaforge.com/forum/topic/26223-problem-with-utf-8

**Comment by omar84** [comment]
i tested with joomla 2.5.6, NRSS v2.0, put some arabic title, it was displayed without any issues.

**Comment by mark-up** [comment]
Thanks. I couldn't replicate it either, but I committed a patch for this yesterday:
https://github.com/NinjaForge/Ninja-RSS-Syndicator/commit/40988948bc6742a74866545392d86b8cfbbefa78

Not sure if it works... still waiting on feedback from the user.
