### ISSUE TITLE
Articles *not* published to the 'Public' usergroup showing up in feeds

### ISSUE THREAD

**Issue by mark-up** [NinjaForge/Ninja-RSS-Syndicator#2]
Articles that are restricted to registered and above should not show in the feed.

This was seen in the J2.5 version, so probably exists in the 3.0 version as well.

**Comment by omar84** [comment]
fixed in both versions, uploaded to repo. please test and confirm, then republish

**Comment by mark-up** [comment]
Thanks, this has been tested and works for me. Awaiting feedback from the original reported of the bug before I close this.

**Comment by mark-up** [comment]
This has been confirmed working. Thanks, Omar.
