### ISSUE TITLE
Installing a new version over an existing version removes the existing feeds

### ISSUE THREAD

**Issue by mark-up** [NinjaForge/Ninja-RSS-Syndicator#4]
Uninstalling should not remove feeds, and upgrading should not affect existing feeds and feed settings at all.

**Comment by omar84** [comment]
upgrading now will not remove the component's db tables for v 3.0, but why should uninstalling keep them as well?

**Comment by mark-up** [comment]
> why should uninstalling keep them as well?

There are instances where keeping the tables is ideal. However, I concede that this isn't often.
