### ISSUE TITLE
'Read More...' text ignoring language files

### ISSUE THREAD

**Issue by mark-up** [NinjaForge/Ninja-RSS-Syndicator#6]
See http://ninjaforge.com/forum/topic/26186-how-translate-the-qread-moreq-in-the-rss-feed#p32909

**Comment by omar84** [comment]
Hi Mark, 

there were no language files for this component, i created both front-end and back-end language files. updated the repo.
users should create installable packages of their own languages if they want to change the language.

please confirm and re-release.
